// Mocks generated by Mockito 5.4.6 from annotations
// in simpleshoppinglist/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simpleshoppinglist/data/models/cart.dart' as _i5;
import 'package:simpleshoppinglist/sources/hive/dto/cart_dto.dart' as _i2;
import 'package:simpleshoppinglist/sources/hive/dto/cart_item_dto.dart' as _i6;
import 'package:simpleshoppinglist/sources/hive/hive_source.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCartDto_0 extends _i1.SmartFake implements _i2.CartDto {
  _FakeCartDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HiveSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveSource extends _i1.Mock implements _i3.HiveSource {
  MockHiveSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get cartsCount =>
      (super.noSuchMethod(Invocation.getter(#cartsCount), returnValue: 0)
          as int);

  @override
  _i4.Future<List<_i2.CartDto>> get carts =>
      (super.noSuchMethod(
            Invocation.getter(#carts),
            returnValue: _i4.Future<List<_i2.CartDto>>.value(<_i2.CartDto>[]),
          )
          as _i4.Future<List<_i2.CartDto>>);

  @override
  _i4.Stream<List<_i2.CartDto>> get cartsStream =>
      (super.noSuchMethod(
            Invocation.getter(#cartsStream),
            returnValue: _i4.Stream<List<_i2.CartDto>>.empty(),
          )
          as _i4.Stream<List<_i2.CartDto>>);

  @override
  set selectedCart(_i5.Cart? value) => super.noSuchMethod(
    Invocation.setter(#selectedCart, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i6.CartItemDto>> get cartItems =>
      (super.noSuchMethod(
            Invocation.getter(#cartItems),
            returnValue: _i4.Future<List<_i6.CartItemDto>>.value(
              <_i6.CartItemDto>[],
            ),
          )
          as _i4.Future<List<_i6.CartItemDto>>);

  @override
  _i4.Stream<List<_i6.CartItemDto>> get cartItemsStream =>
      (super.noSuchMethod(
            Invocation.getter(#cartItemsStream),
            returnValue: _i4.Stream<List<_i6.CartItemDto>>.empty(),
          )
          as _i4.Stream<List<_i6.CartItemDto>>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCarts() =>
      (super.noSuchMethod(
            Invocation.method(#clearCarts, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.CartDto> addCart(_i2.CartDto? cart) =>
      (super.noSuchMethod(
            Invocation.method(#addCart, [cart]),
            returnValue: _i4.Future<_i2.CartDto>.value(
              _FakeCartDto_0(this, Invocation.method(#addCart, [cart])),
            ),
          )
          as _i4.Future<_i2.CartDto>);

  @override
  _i2.CartDto? getCart(int? id) =>
      (super.noSuchMethod(Invocation.method(#getCart, [id])) as _i2.CartDto?);

  @override
  _i4.Future<void> setCart(_i2.CartDto? cart) =>
      (super.noSuchMethod(
            Invocation.method(#setCart, [cart]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeCart(_i2.CartDto? cart) =>
      (super.noSuchMethod(
            Invocation.method(#removeCart, [cart]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> openCartsBox() =>
      (super.noSuchMethod(
            Invocation.method(#openCartsBox, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#clearCartItems, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addCartItem(_i6.CartItemDto? cartItem) =>
      (super.noSuchMethod(
            Invocation.method(#addCartItem, [cartItem]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i6.CartItemDto? getCartItem(String? id) =>
      (super.noSuchMethod(Invocation.method(#getCartItem, [id]))
          as _i6.CartItemDto?);

  @override
  _i4.Future<void> openCartItemsBox() =>
      (super.noSuchMethod(
            Invocation.method(#openCartItemsBox, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
